name: datn_mobile
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.8.0"

dependencies:
  auto_route: ^10.1.2
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  duration: ^4.0.3
  flash: ^3.1.1
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_secure_storage_x: ^11.3.0
  flutter_secure_storage_linux: ^2.0.1
  hive_ce_flutter: ^2.3.2
  internet_connection_checker_plus: ^2.8.0
  intl: ^0.20.2
  multiple_result: ^5.2.0
  path_provider: ^2.1.5
  platform_info: ^5.0.0
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker_dio_logger: ^4.9.3
  talker_flutter: ^4.9.3
  flutter_hooks: ^0.21.3
  json_annotation: ^4.9.0
  retrofit: ^4.7.2
  dotenv: ^4.2.0
  shadcn_ui: ^0.31.8
  lucide_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^3.0.0-dev.17
  slang_build_runner: ^4.8.1
  spot: ^0.16.0
  very_good_analysis: ^9.0.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.0
  flutter_pre_commit: ^0.2.4

flutter:
  uses-material-design: true
